### ISSUE TITLE
Improve progress output

### ISSUE THREAD

**Issue by jancimajek** [jancimajek/dashcam-backup#12]
## Tasks

- [x] Change the progress output to keep in the same line:
  - [x] Should overwrite the progress line
  - [x] Should work correctly when a new line is shorter than the previous
  - [x] Should NOT show progress in multiple files like now (, i.e. NOT one file per line)
  - [x] Should work normally for non-progress output
