### ISSUE TITLE
Copy only correct file types + make find more robust

### ISSUE THREAD

**Issue by jancimajek** [jancimajek/dashcam-backup#20]
## Tasks

- [x] Copy only correct file types:
  - [x] `*.log` for GPS logs
  - [x] `*.mov` for videos
  - [x] extension should be case insensitive
- [x] Don't fail if `find` encounters file/directory it cannot read (`Operation not permitted` error)
